name: daily_diary
description: A diary that starts with a blank page every day (while saving the previous ones)
publish_to: 'none'

version: 1.4.1+13

environment:
  sdk: '>=2.23.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  toml: ^0.14.0
  shared_preferences: ^2.0.15
  file_picker: ^6.0.0
  flutter_window_close: ^1.0.0
  shared_storage: ^0.8.0
  archive: ^3.3.7
  flex_color_picker: ^3.3.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
