name: daily_diary
description: A diary that starts with a blank page every day (while saving the previous ones)
publish_to: 'none'

version: 1.4.3+15

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  toml: ^0.15.0
  shared_preferences: ^2.0.15
  file_picker: 8.1.3
  flutter_window_close: ^1.0.0
  archive: ^3.3.7
  flex_color_picker: ^3.3.0
  url_launcher: ^6.2.1
  shared_storage:
    git:
      url: https://github.com/AlexBacich/shared-storage
      ref: 8784c39b909324df8913dd30fa416b8a50d55f49

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
